// Dados de exemplo para o dashboard de saúde

// Estatísticas gerais
export const statsData = {
  totalHospitals: 8457,
  totalBeds: 489632,
  averageOccupancy: 72.5,
  patientsServed: 1245789,
}

// Dados das regiões
export const regionData = [
  {
    id: "north",
    name: "Norte",
    hospitals: 845,
    urbanAccessIndex: 78,
    ruralAccessIndex: 42,
    doctors: 32500,
    beds: 95000,
    population: 18000000,
    equipment: 65,
    healthcareSpending: 12.5, // bilhões por ano
    healthcareWorkers: 125000,
    ambulances: 1250,
    specialistCoverage: 58,
    vaccineDistribution: 82,
    primaryCareUnits: 3200,
  },
  {
    id: "northeast",
    name: "Nordeste",
    hospitals: 2187,
    urbanAccessIndex: 82,
    ruralAccessIndex: 48,
    doctors: 78000,
    beds: 198000,
    population: 57000000,
    equipment: 72,
    healthcareSpending: 28.7,
    healthcareWorkers: 320000,
    ambulances: 3800,
    specialistCoverage: 65,
    vaccineDistribution: 88,
    primaryCareUnits: 8500,
  },
  {
    id: "central-west",
    name: "Centro-Oeste",
    hospitals: 912,
    urbanAccessIndex: 88,
    ruralAccessIndex: 56,
    doctors: 45000,
    beds: 82000,
    population: 16000000,
    equipment: 78,
    healthcareSpending: 15.3,
    healthcareWorkers: 145000,
    ambulances: 1450,
    specialistCoverage: 72,
    vaccineDistribution: 90,
    primaryCareUnits: 2800,
  },
  {
    id: "southeast",
    name: "Sudeste",
    hospitals: 3292,
    urbanAccessIndex: 94,
    ruralAccessIndex: 62,
    doctors: 185000,
    beds: 310000,
    population: 89000000,
    equipment: 92,
    healthcareSpending: 65.8,
    healthcareWorkers: 580000,
    ambulances: 6200,
    specialistCoverage: 88,
    vaccineDistribution: 95,
    primaryCareUnits: 12500,
  },
  {
    id: "south",
    name: "Sul",
    hospitals: 1221,
    urbanAccessIndex: 92,
    ruralAccessIndex: 58,
    doctors: 82000,
    beds: 154000,
    population: 30000000,
    equipment: 85,
    healthcareSpending: 32.4,
    healthcareWorkers: 280000,
    ambulances: 2900,
    specialistCoverage: 82,
    vaccineDistribution: 93,
    primaryCareUnits: 5800,
  },
]

// Dados dos hospitais
export const hospitalData = [
  // NORTE
  {
    id: "hosp-n1",
    name: "Hospital Regional de Belém",
    region: "Norte",
    city: "Belém",
    state: "PA",
    beds: 450,
    occupancy: 78,
    doctors: 180,
    nurses: 380,
    specialties: ["Cardiologia", "Neurologia", "Pediatria", "Ortopedia"],
    patientOutcomes: [
      { month: "Jan", successRate: 76 },
      { month: "Fev", successRate: 78 },
      { month: "Mar", successRate: 77 },
      { month: "Abr", successRate: 80 },
      { month: "Mai", successRate: 82 },
      { month: "Jun", successRate: 81 },
    ],
    waitingTime: 45, // minutos
    emergencyCapacity: 85,
    icuBeds: 45,
    publicFunding: true,
  },
  {
    id: "hosp-n2",
    name: "Hospital Universitário de Manaus",
    region: "Norte",
    city: "Manaus",
    state: "AM",
    beds: 520,
    occupancy: 82,
    doctors: 210,
    nurses: 420,
    specialties: ["Infectologia", "Pneumologia", "Pediatria", "Cirurgia Geral"],
    patientOutcomes: [
      { month: "Jan", successRate: 74 },
      { month: "Fev", successRate: 75 },
      { month: "Mar", successRate: 76 },
      { month: "Abr", successRate: 78 },
      { month: "Mai", successRate: 80 },
      { month: "Jun", successRate: 79 },
    ],
    waitingTime: 52,
    emergencyCapacity: 90,
    icuBeds: 55,
    publicFunding: true,
  },
  {
    id: "hosp-n3",
    name: "Hospital Santa Júlia",
    region: "Norte",
    city: "Macapá",
    state: "AP",
    beds: 320,
    occupancy: 75,
    doctors: 120,
    nurses: 280,
    specialties: ["Cardiologia", "Ortopedia", "Ginecologia", "Pediatria"],
    patientOutcomes: [
      { month: "Jan", successRate: 79 },
      { month: "Fev", successRate: 80 },
      { month: "Mar", successRate: 81 },
      { month: "Abr", successRate: 82 },
      { month: "Mai", successRate: 84 },
      { month: "Jun", successRate: 83 },
    ],
    waitingTime: 38,
    emergencyCapacity: 70,
    icuBeds: 32,
    publicFunding: false,
  },
  {
    id: "hosp-n4",
    name: "Hospital Geral de Palmas",
    region: "Norte",
    city: "Palmas",
    state: "TO",
    beds: 380,
    occupancy: 71,
    doctors: 150,
    nurses: 320,
    specialties: ["Neurologia", "Oncologia", "Urologia", "Pediatria"],
    patientOutcomes: [
      { month: "Jan", successRate: 77 },
      { month: "Fev", successRate: 78 },
      { month: "Mar", successRate: 76 },
      { month: "Abr", successRate: 79 },
      { month: "Mai", successRate: 81 },
      { month: "Jun", successRate: 80 },
    ],
    waitingTime: 42,
    emergencyCapacity: 75,
    icuBeds: 38,
    publicFunding: true,
  },
  {
    id: "hosp-n5",
    name: "Hospital Adventista de Belém",
    region: "Norte",
    city: "Belém",
    state: "PA",
    beds: 280,
    occupancy: 68,
    doctors: 110,
    nurses: 240,
    specialties: ["Cardiologia", "Pediatria", "Clínica Médica", "Obstetrícia"],
    patientOutcomes: [
      { month: "Jan", successRate: 82 },
      { month: "Fev", successRate: 83 },
      { month: "Mar", successRate: 84 },
      { month: "Abr", successRate: 85 },
      { month: "Mai", successRate: 86 },
      { month: "Jun", successRate: 85 },
    ],
    waitingTime: 35,
    emergencyCapacity: 65,
    icuBeds: 28,
    publicFunding: false,
  },

  // NORDESTE
  {
    id: "hosp-ne1",
    name: "Hospital das Clínicas de Recife",
    region: "Nordeste",
    city: "Recife",
    state: "PE",
    beds: 680,
    occupancy: 84,
    doctors: 280,
    nurses: 580,
    specialties: ["Cardiologia", "Neurologia", "Oncologia", "Ortopedia", "Pediatria"],
    patientOutcomes: [
      { month: "Jan", successRate: 78 },
      { month: "Fev", successRate: 79 },
      { month: "Mar", successRate: 80 },
      { month: "Abr", successRate: 82 },
      { month: "Mai", successRate: 83 },
      { month: "Jun", successRate: 82 },
    ],
    waitingTime: 48,
    emergencyCapacity: 95,
    icuBeds: 68,
    publicFunding: true,
  },
  {
    id: "hosp-ne2",
    name: "Hospital São Lucas",
    region: "Nordeste",
    city: "Salvador",
    state: "BA",
    beds: 720,
    occupancy: 86,
    doctors: 310,
    nurses: 620,
    specialties: ["Cardiologia", "Neurologia", "Oncologia", "Urologia", "Pediatria"],
    patientOutcomes: [
      { month: "Jan", successRate: 80 },
      { month: "Fev", successRate: 81 },
      { month: "Mar", successRate: 82 },
      { month: "Abr", successRate: 83 },
      { month: "Mai", successRate: 85 },
      { month: "Jun", successRate: 84 },
    ],
    waitingTime: 42,
    emergencyCapacity: 100,
    icuBeds: 72,
    publicFunding: false,
  },
  {
    id: "hosp-ne3",
    name: "Hospital Universitário de Fortaleza",
    region: "Nordeste",
    city: "Fortaleza",
    state: "CE",
    beds: 580,
    occupancy: 79,
    doctors: 240,
    nurses: 490,
    specialties: ["Infectologia", "Pneumologia", "Pediatria", "Cirurgia Geral"],
    patientOutcomes: [
      { month: "Jan", successRate: 76 },
      { month: "Fev", successRate: 77 },
      { month: "Mar", successRate: 78 },
      { month: "Abr", successRate: 80 },
      { month: "Mai", successRate: 81 },
      { month: "Jun", successRate: 80 },
    ],
    waitingTime: 50,
    emergencyCapacity: 85,
    icuBeds: 58,
    publicFunding: true,
  },
  {
    id: "hosp-ne4",
    name: "Hospital Santa Isabel",
    region: "Nordeste",
    city: "João Pessoa",
    state: "PB",
    beds: 420,
    occupancy: 75,
    doctors: 180,
    nurses: 380,
    specialties: ["Cardiologia", "Ortopedia", "Ginecologia", "Pediatria"],
    patientOutcomes: [
      { month: "Jan", successRate: 81 },
      { month: "Fev", successRate: 82 },
      { month: "Mar", successRate: 83 },
      { month: "Abr", successRate: 84 },
      { month: "Mai", successRate: 85 },
      { month: "Jun", successRate: 84 },
    ],
    waitingTime: 40,
    emergencyCapacity: 75,
    icuBeds: 42,
    publicFunding: false,
  },
  {
    id: "hosp-ne5",
    name: "Hospital Getúlio Vargas",
    region: "Nordeste",
    city: "Teresina",
    state: "PI",
    beds: 480,
    occupancy: 82,
    doctors: 200,
    nurses: 420,
    specialties: ["Neurologia", "Oncologia", "Urologia", "Pediatria"],
    patientOutcomes: [
      { month: "Jan", successRate: 75 },
      { month: "Fev", successRate: 76 },
      { month: "Mar", successRate: 77 },
      { month: "Abr", successRate: 79 },
      { month: "Mai", successRate: 80 },
      { month: "Jun", successRate: 79 },
    ],
    waitingTime: 45,
    emergencyCapacity: 80,
    icuBeds: 48,
    publicFunding: true,
  },

  // CENTRO-OESTE
  {
    id: "hosp-co1",
    name: "Hospital de Base do Distrito Federal",
    region: "Centro-Oeste",
    city: "Brasília",
    state: "DF",
    beds: 650,
    occupancy: 83,
    doctors: 270,
    nurses: 550,
    specialties: ["Cardiologia", "Neurologia", "Oncologia", "Ortopedia", "Pediatria"],
    patientOutcomes: [
      { month: "Jan", successRate: 79 },
      { month: "Fev", successRate: 80 },
      { month: "Mar", successRate: 81 },
      { month: "Abr", successRate: 83 },
      { month: "Mai", successRate: 84 },
      { month: "Jun", successRate: 83 },
    ],
    waitingTime: 46,
    emergencyCapacity: 95,
    icuBeds: 65,
    publicFunding: true,
  },
  {
    id: "hosp-co2",
    name: "Hospital Santa Helena",
    region: "Centro-Oeste",
    city: "Goiânia",
    state: "GO",
    beds: 480,
    occupancy: 78,
    doctors: 210,
    nurses: 420,
    specialties: ["Cardiologia", "Neurologia", "Oncologia", "Urologia", "Pediatria"],
    patientOutcomes: [
      { month: "Jan", successRate: 82 },
      { month: "Fev", successRate: 83 },
      { month: "Mar", successRate: 84 },
      { month: "Abr", successRate: 85 },
      { month: "Mai", successRate: 86 },
      { month: "Jun", successRate: 85 },
    ],
    waitingTime: 38,
    emergencyCapacity: 85,
    icuBeds: 48,
    publicFunding: false,
  },
  {
    id: "hosp-co3",
    name: "Hospital Universitário de Cuiabá",
    region: "Centro-Oeste",
    city: "Cuiabá",
    state: "MT",
    beds: 420,
    occupancy: 76,
    doctors: 180,
    nurses: 380,
    specialties: ["Infectologia", "Pneumologia", "Pediatria", "Cirurgia Geral"],
    patientOutcomes: [
      { month: "Jan", successRate: 77 },
      { month: "Fev", successRate: 78 },
      { month: "Mar", successRate: 79 },
      { month: "Abr", successRate: 81 },
      { month: "Mai", successRate: 82 },
      { month: "Jun", successRate: 81 },
    ],
    waitingTime: 44,
    emergencyCapacity: 75,
    icuBeds: 42,
    publicFunding: true,
  },
  {
    id: "hosp-co4",
    name: "Hospital Regional de Campo Grande",
    region: "Centro-Oeste",
    city: "Campo Grande",
    state: "MS",
    beds: 380,
    occupancy: 72,
    doctors: 160,
    nurses: 340,
    specialties: ["Cardiologia", "Ortopedia", "Ginecologia", "Pediatria"],
    patientOutcomes: [
      { month: "Jan", successRate: 78 },
      { month: "Fev", successRate: 79 },
      { month: "Mar", successRate: 80 },
      { month: "Abr", successRate: 81 },
      { month: "Mai", successRate: 82 },
      { month: "Jun", successRate: 81 },
    ],
    waitingTime: 42,
    emergencyCapacity: 70,
    icuBeds: 38,
    publicFunding: true,
  },

  // SUDESTE
  {
    id: "hosp-se1",
    name: "Hospital das Clínicas de São Paulo",
    region: "Sudeste",
    city: "São Paulo",
    state: "SP",
    beds: 950,
    occupancy: 88,
    doctors: 420,
    nurses: 880,
    specialties: ["Cardiologia", "Neurologia", "Oncologia", "Ortopedia", "Pediatria", "Transplantes"],
    patientOutcomes: [
      { month: "Jan", successRate: 82 },
      { month: "Fev", successRate: 83 },
      { month: "Mar", successRate: 84 },
      { month: "Abr", successRate: 85 },
      { month: "Mai", successRate: 87 },
      { month: "Jun", successRate: 86 },
    ],
    waitingTime: 52,
    emergencyCapacity: 120,
    icuBeds: 95,
    publicFunding: true,
  },
  {
    id: "hosp-se2",
    name: "Hospital Albert Einstein",
    region: "Sudeste",
    city: "São Paulo",
    state: "SP",
    beds: 720,
    occupancy: 82,
    doctors: 380,
    nurses: 720,
    specialties: ["Cardiologia", "Neurologia", "Oncologia", "Urologia", "Pediatria", "Cirurgia Robótica"],
    patientOutcomes: [
      { month: "Jan", successRate: 88 },
      { month: "Fev", successRate: 89 },
      { month: "Mar", successRate: 90 },
      { month: "Abr", successRate: 91 },
      { month: "Mai", successRate: 92 },
      { month: "Jun", successRate: 91 },
    ],
    waitingTime: 25,
    emergencyCapacity: 100,
    icuBeds: 72,
    publicFunding: false,
  },
  {
    id: "hosp-se3",
    name: "Hospital das Clínicas da UFMG",
    region: "Sudeste",
    city: "Belo Horizonte",
    state: "MG",
    beds: 680,
    occupancy: 85,
    doctors: 320,
    nurses: 650,
    specialties: ["Cardiologia", "Neurologia", "Oncologia", "Ortopedia", "Pediatria"],
    patientOutcomes: [
      { month: "Jan", successRate: 80 },
      { month: "Fev", successRate: 81 },
      { month: "Mar", successRate: 82 },
      { month: "Abr", successRate: 83 },
      { month: "Mai", successRate: 84 },
      { month: "Jun", successRate: 83 },
    ],
    waitingTime: 48,
    emergencyCapacity: 95,
    icuBeds: 68,
    publicFunding: true,
  },
  {
    id: "hosp-se4",
    name: "Hospital Universitário Pedro Ernesto",
    region: "Sudeste",
    city: "Rio de Janeiro",
    state: "RJ",
    beds: 620,
    occupancy: 84,
    doctors: 280,
    nurses: 580,
    specialties: ["Infectologia", "Pneumologia", "Pediatria", "Cirurgia Geral", "Oncologia"],
    patientOutcomes: [
      { month: "Jan", successRate: 79 },
      { month: "Fev", successRate: 80 },
      { month: "Mar", successRate: 81 },
      { month: "Abr", successRate: 82 },
      { month: "Mai", successRate: 83 },
      { month: "Jun", successRate: 82 },
    ],
    waitingTime: 50,
    emergencyCapacity: 90,
    icuBeds: 62,
    publicFunding: true,
  },
  {
    id: "hosp-se5",
    name: "Hospital Sírio-Libanês",
    region: "Sudeste",
    city: "São Paulo",
    state: "SP",
    beds: 650,
    occupancy: 80,
    doctors: 350,
    nurses: 680,
    specialties: ["Cardiologia", "Neurologia", "Oncologia", "Urologia", "Pediatria", "Cirurgia Robótica"],
    patientOutcomes: [
      { month: "Jan", successRate: 89 },
      { month: "Fev", successRate: 90 },
      { month: "Mar", successRate: 91 },
      { month: "Abr", successRate: 92 },
      { month: "Mai", successRate: 93 },
      { month: "Jun", successRate: 92 },
    ],
    waitingTime: 22,
    emergencyCapacity: 95,
    icuBeds: 65,
    publicFunding: false,
  },
  {
    id: "hosp-se6",
    name: "Hospital Santa Marcelina",
    region: "Sudeste",
    city: "São Paulo",
    state: "SP",
    beds: 580,
    occupancy: 86,
    doctors: 250,
    nurses: 520,
    specialties: ["Cardiologia", "Ortopedia", "Ginecologia", "Pediatria", "Oncologia"],
    patientOutcomes: [
      { month: "Jan", successRate: 81 },
      { month: "Fev", successRate: 82 },
      { month: "Mar", successRate: 83 },
      { month: "Abr", successRate: 84 },
      { month: "Mai", successRate: 85 },
      { month: "Jun", successRate: 84 },
    ],
    waitingTime: 45,
    emergencyCapacity: 85,
    icuBeds: 58,
    publicFunding: true,
  },

  // SUL
  {
    id: "hosp-s1",
    name: "Hospital de Clínicas de Porto Alegre",
    region: "Sul",
    city: "Porto Alegre",
    state: "RS",
    beds: 780,
    occupancy: 85,
    doctors: 340,
    nurses: 720,
    specialties: ["Cardiologia", "Neurologia", "Oncologia", "Ortopedia", "Pediatria", "Transplantes"],
    patientOutcomes: [
      { month: "Jan", successRate: 83 },
      { month: "Fev", successRate: 84 },
      { month: "Mar", successRate: 85 },
      { month: "Abr", successRate: 86 },
      { month: "Mai", successRate: 87 },
      { month: "Jun", successRate: 86 },
    ],
    waitingTime: 45,
    emergencyCapacity: 110,
    icuBeds: 78,
    publicFunding: true,
  },
  {
    id: "hosp-s2",
    name: "Hospital Nossa Senhora das Graças",
    region: "Sul",
    city: "Curitiba",
    state: "PR",
    beds: 580,
    occupancy: 79,
    doctors: 260,
    nurses: 520,
    specialties: ["Cardiologia", "Neurologia", "Oncologia", "Urologia", "Pediatria"],
    patientOutcomes: [
      { month: "Jan", successRate: 84 },
      { month: "Fev", successRate: 85 },
      { month: "Mar", successRate: 86 },
      { month: "Abr", successRate: 87 },
      { month: "Mai", successRate: 88 },
      { month: "Jun", successRate: 87 },
    ],
    waitingTime: 35,
    emergencyCapacity: 85,
    icuBeds: 58,
    publicFunding: false,
  },
  {
    id: "hosp-s3",
    name: "Hospital Universitário de Florianópolis",
    region: "Sul",
    city: "Florianópolis",
    state: "SC",
    beds: 520,
    occupancy: 82,
    doctors: 230,
    nurses: 480,
    specialties: ["Infectologia", "Pneumologia", "Pediatria", "Cirurgia Geral", "Oncologia"],
    patientOutcomes: [
      { month: "Jan", successRate: 81 },
      { month: "Fev", successRate: 82 },
      { month: "Mar", successRate: 83 },
      { month: "Abr", successRate: 84 },
      { month: "Mai", successRate: 85 },
      { month: "Jun", successRate: 84 },
    ],
    waitingTime: 42,
    emergencyCapacity: 80,
    icuBeds: 52,
    publicFunding: true,
  },
  {
    id: "hosp-s4",
    name: "Hospital Moinhos de Vento",
    region: "Sul",
    city: "Porto Alegre",
    state: "RS",
    beds: 480,
    occupancy: 78,
    doctors: 220,
    nurses: 450,
    specialties: ["Cardiologia", "Ortopedia", "Ginecologia", "Pediatria", "Oncologia"],
    patientOutcomes: [
      { month: "Jan", successRate: 86 },
      { month: "Fev", successRate: 87 },
      { month: "Mar", successRate: 88 },
      { month: "Abr", successRate: 89 },
      { month: "Mai", successRate: 90 },
      { month: "Jun", successRate: 89 },
    ],
    waitingTime: 30,
    emergencyCapacity: 75,
    icuBeds: 48,
    publicFunding: false,
  },
  {
    id: "hosp-s5",
    name: "Hospital Ernesto Dornelles",
    region: "Sul",
    city: "Porto Alegre",
    state: "RS",
    beds: 420,
    occupancy: 76,
    doctors: 180,
    nurses: 380,
    specialties: ["Cardiologia", "Neurologia", "Oncologia", "Urologia", "Pediatria"],
    patientOutcomes: [
      { month: "Jan", successRate: 82 },
      { month: "Fev", successRate: 83 },
      { month: "Mar", successRate: 84 },
      { month: "Abr", successRate: 85 },
      { month: "Mai", successRate: 86 },
      { month: "Jun", successRate: 85 },
    ],
    waitingTime: 38,
    emergencyCapacity: 70,
    icuBeds: 42,
    publicFunding: false,
  },
]

// Função para inicializar o banco de dados com os dados de exemplo
export async function initializeDatabase(db) {
  try {
    // Inserir dados de estatísticas
    await db.collection("stats").doc("overall").set(statsData)
    console.log("Dados de estatísticas inseridos com sucesso")

    // Inserir dados de regiões
    for (const region of regionData) {
      await db.collection("regions").doc(region.id).set(region)
    }
    console.log("Dados de regiões inseridos com sucesso")

    // Inserir dados de hospitais
    for (const hospital of hospitalData) {
      await db.collection("hospitals").doc(hospital.id).set(hospital)
    }
    console.log("Dados de hospitais inseridos com sucesso")

    return { success: true, message: "Banco de dados inicializado com sucesso" }
  } catch (error) {
    console.error("Erro ao inicializar banco de dados:", error)
    throw error
  }
}
